### ISSUE TITLE
Less 2.x support

### ISSUE THREAD

**Issue by denov** [gabrysbiz/lesscss-compiler#2]
what's the status of supporting Less 2.x?

**Comment by agabrys** [comment]
Probably I will not add support for [Less](http://lesscss.org/) 2.X, because Less authors don't provide scripts compatible with [Rhino](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino). Unfortunately I don't have enough free time to create it on my own.

I will add support for it, if I found any way to simple execute [Less](http://lesscss.org/) 2.X.
In near feature I will work on Support for Source map #3.
